###############################
# DEFAULT 
###############################
enabled: true
developer: false
scheduler: false
worker: false
name: inventory
replicas: 1
image:
    repository: spaceone
    name: inventory
    version: latest
imagePullPolicy: IfNotPresent

# Overwrite database
database: {}

# Overwrite application config
application: {}

# Overwrite scheduler config
#application_scheduler: {}
application_scheduler: 
    QUEUES:
        collector_q:
            backend: spaceone.core.queue.redis_queue.RedisQueue
            host: redis
            port: 6379
            channel: collector

    SCHEDULERS:
        hourly_scheduler:
            backend: spaceone.inventory.scheduler.inventory_scheduler.InventoryHourlyScheduler
            queue: collector_q
            interval: 1
            minute: ':00'

        interval_scheduler:
            backend: spaceone.inventory.scheduler.interval_scheduler.InventoryIntervalScheduler
            queue: collector_q
            interval: 60


        cleanup_scheduler:
            backend: spaceone.inventory.scheduler.cleanup_scheduler.CleanupScheduler
            queue: collector_q
            interval: 1
            minute: ':35'
#   TOKEN_INFO:
#       protocol:
#       config:
#           host: consul
#       uri: debug/supervisor/TOKEN
# OR
#   TOKEN: xxxxxxx
#
# Overwrite worker config
#application_worker: {}
application_worker:
    QUEUES:
        collector_q:
            backend: spaceone.core.queue.redis_queue.RedisQueue
            host: redis
            port: 6379
            channel: collector


    WORKERS:
        collector_worker:
            backend: spaceone.core.scheduler.worker.BaseWorker
            queue: collector_q
            pool: 4

#   TOKEN_INFO:
#       protocol:
#       config:
#           host: consul
#       uri: debug/supervisor/TOKEN
# OR
#   TOKEN: xxxxxxx
#
# local sidecar
##########################
#sidecar:


##########################
# Local volumes
##########################
volumes:
    - name: timezone
      hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
    - name: log-volume
      emptyDir: {}

#######################
# global variable
#######################
global:
    shared: {}
    sidecar: []
#        - name: mongos
#          image: mongo:4.4.0-bionic
#          command: [ 'mongos', '--config', '/mnt/mongos.yml', '--bind_ip_all' ]
#          volumeMounts:
#            - name: mongos-conf
#              mountPath: /mnt/mongos.yml
#              subPath: mongos.yml
#              readOnly: true
#            - name: mongo-shard-key
#              mountPath: /opt/mongos/mongo-shard.pem
#              subPath: mongo-shard.pem
#              readOnly: true
#
    volumes: []
#        - name: mongo-shard-key
#          secret:
#              defaultMode: 0400
#              secretName: mongo-shard-key
#        - name: mongos-conf
#          configMap:
#              name: mongos-conf
#        - name: shared-conf
#          configMap:
#              name: shared-conf

    
# Service
service:
    type: ClusterIP
    annotations:
        nil: nil
    ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          protocol: TCP
